language: node_js

env:
  - AZURE_WA_SITE=weareus-website

script:
 - npm run lint
 - npm audit
 - npm run compile

after_success:
 - rm -rf node_modules
 - npm install --production
 - mkdir deploy
 - cp -R client deploy
 - cp -R public deploy
 - cp -R node_modules deploy
 - cp -R server deploy
 - cp .env.example deploy
 - cp .npmrc deploy
 - cp package.json deploy
 - cp server.js deploy
 - cp web.config deploy
 - zip -r deploy.zip deploy
 - curl --ftp-create-dirs
       -T deploy.zip
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@waws-prod-dm1-095.ftp.azurewebsites.windows.net/site/wwwroot


