language: node_js

script:
- npm run lint
- npm audit

before_deploy:
- printf '%s\n' 'CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID}' 'CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN}' > .env

deploy:
  provider: heroku
  api_key:
    secure: Ta6cYi82bCcYZ3d2puakJslfzuXKYeKSmT8aNYhusoPgtCJbjvaCNXHWRRcxLgbQEIbI6xSvwIYBv60h0tapxiwHUkbvmbVjOifzWpwmnA360U52lgXEwqYdLutbKiymsxs9kQqKM4yQ1HTeH+drcBLEX+hgMoSg1i5PKzrrHW29WxSNZB/owqILCGdivB57Zj5ELc6Ovsa/uDsnN+0HC4ioWgpxOQ7VvlDojHbjzbuLSxqVgAZFoXfY0cZ0Cw3q/7QRLHZlGZempPqFdRFNKURXTbnjQ/kSdU66M0wDCLfeTh8OjVvbj/AKZXGoXJlGfCcXwy9kQinc452HwtkGRtcfFvR9249BkJfi9jGBe5MQua1CKGDLw4iVtiCZjeVUfjd44IvjtyNKOtiD2IAAFgcwY8Jtcl86zs0F62IypCX6ruTMvaOuSSDYT6hP9g+DK1xQT2EnbvLsJhh1SEVlfqKlVTJA5RQ/QohpCRDv4yPEfwLxY8TOFdEeCM47JVhK4Em0JFELsdMpqEMQ+HXnVxzz19Qn7BuLlYHXVkrEpO9mGciCXzeIwEI4qnSSwoNHLb1ZVz3ok0EudMTwbcF5G8wdihHxNeD1tThpPbAI1F8Q509IXw2K/qgg5I/K5i+r3hYTRw/JkKjqwLf0SlN70YTRTq15ndtpKoOxNU9la9g=
  app: weareus
  on:
    repo: We-Are-Us/site
