language: node_js

script:
- npm run lint
- npm audit

before_deploy:
- npm run compile
- printf '%s\n' 'CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID}' 'CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN}' > .env

deploy:
  provider: heroku
  api_key: ${HEROKU_API_KEY}
  app: weareus
  on:
    repo: We-Are-Us/site
