language: node_js

env:
  - NODE_ENV=production

script:
 - npm run lint
 - npm audit
 - npm run compile

after_success:
 - mkdir deploy
 - cp -r public deploy/public
 - cp -r server deploy/server
 - cp .env.example deploy
 - cp .npmrc deploy
 - cp package.json deploy
 - cp server.js deploy
 - cp web.config deploy
 - cd deploy
 - zip -r9 ../deploy.zip .
 - cd ..
 - curl -X POST -u ${KUDU_USERNAME}:${KUDU_PASSWORD} --data-binary @deploy.zip https://${KUDU_SITENAME}.scm.azurewebsites.net/api/zipdeploy