language: node_js

script:
 - npm run lint
 - npm audit

before_deploy:
 - printf '%s\n' 'CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID}' 'CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN}' >.env
 - NODE_ENV=production npm run compile
 - mkdir deploy
 - cp -R public deploy/public
 - cp -R server deploy/server
 - cp .env.example deploy
 - cp .npmrc deploy
 - cp package-lock.json deploy
 - cp package.json deploy
 - cp README.md deploy
 - cp server.js deploy
 - cp web.config deploy
 - cd deploy
 - zip -r9 ../deploy.zip .
 - cd ..
 - unzip -lf deploy.zip

deploy:
  provider: azure_web_apps
  site: weareus-website
  slot: staging
  verbose: true
