language: node_js

env:
  - AZURE_WA_SITE=weareus-website

script:
 - npm run lint
 - npm audit
 - npm run compile

before_deploy:
 - rm -rf node_modules
 - npm install --production
 - curl -L https://aka.ms/InstallAzureCli | bash
deploy:
  provider: azure_web_apps
  on: master