language: node_js

script:
 - npm run lint
 - npm audit
 - printf '%s\n' 'CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID}' 'CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN}' >.env
 - npm run compile

after_success:
 - mkdir deploy
 - cp -R public deploy/public
 - cp -R server deploy/server
 - cp .deployment deploy
 - cp .env.example deploy
 - cp .npmrc deploy
 - cp deploy.cmd deploy
 - cp package-lock.json deploy
 - cp package.json deploy
 - cp README.md deploy
 - cp server.js deploy
 - cp web.config deploy
 - cd deploy
 - zip -r9 ../deploy.zip .
 - cd ..
 - unzip -lf deploy.zip
 - curl -X POST -u ${KUDU_USERNAME}:${KUDU_PASSWORD} --data-binary @deploy.zip https://${KUDU_SITENAME}.scm.azurewebsites.net/api/zipdeploy